Repository googleapis/java-automl, pull requests merged in 2020-10, with the labels that each got.

#325 samples: enabled test and fixed flaky tests
  samples/snippets/src/test/java/com/example/automl/ListModelsTest.java
Labels: cla: yes

#329 build(java): readme.sh should be executable
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#331 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#332 feat: Added text extraction health care option in create model.
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelExportOutputConfig.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelExportOutputConfigOrBuilder.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextExtractionModelMetadata.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextExtractionModelMetadataOrBuilder.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TextProto.java
  proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/io.proto
  proto-google-cloud-automl-v1beta1/src/main/proto/google/cloud/automl/v1beta1/text.proto
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#338 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes

#340 ci(java): suggest formatting fixes
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#344 build(java): auto-approve README regeneration
  .github/workflows/approve-readme.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#345 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#346 chores: removed extra client settings for automl
  samples/snippets/src/main/java/com/beta/automl/ListDatasets.java
  samples/snippets/src/main/java/com/beta/automl/ListModels.java
  samples/snippets/src/main/java/com/example/automl/ListModels.java
Labels: api: automl, cla: yes

#348 build(java): enable snippet-bot
  .github/snippet-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full

#353 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#354 chore: clean up and update renovate.json
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#356 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#357 chore: prep for sample browser
  samples/snippets/src/main/java/com/beta/automl/BatchPredict.java
  samples/snippets/src/main/java/com/beta/automl/DeleteDataset.java
  samples/snippets/src/main/java/com/beta/automl/DeleteModel.java
  samples/snippets/src/main/java/com/beta/automl/DeployModel.java
  samples/snippets/src/main/java/com/beta/automl/GetModelEvaluation.java
  samples/snippets/src/main/java/com/beta/automl/GetOperationStatus.java
  samples/snippets/src/main/java/com/beta/automl/ImportDataset.java
  samples/snippets/src/main/java/com/beta/automl/ListDatasets.java
  samples/snippets/src/main/java/com/beta/automl/ListModelEvaluations.java
  samples/snippets/src/main/java/com/beta/automl/ListModels.java
  samples/snippets/src/main/java/com/beta/automl/TablesBatchPredictBigQuery.java
  samples/snippets/src/main/java/com/beta/automl/TablesCreateDataset.java
  samples/snippets/src/main/java/com/beta/automl/TablesCreateModel.java
  samples/snippets/src/main/java/com/beta/automl/TablesImportDataset.java
  samples/snippets/src/main/java/com/beta/automl/TablesPredict.java
  samples/snippets/src/main/java/com/beta/automl/UndeployModel.java
Labels: automerge, cla: yes

#358 fix: unbreak cloud docs
  samples/snippets/src/main/java/com/beta/automl/ImportDataset.java
Labels: api: automl, cla: yes

#361 chore: add region tags for sample browser
  samples/snippets/src/main/java/com/beta/automl/GetModel.java
Labels: automerge, cla: yes

#363 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#360 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#366 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#369 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#372 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#373 chore: moving vision automl samples
  samples/install-without-bom/resources/dandelion.jpg
  samples/snapshot/resources/dandelion.jpg
  samples/snippets/resources/dandelion.jpg
  samples/snippets/src/main/java/com/google/cloud/vision/ClassificationDeployModel.java
  samples/snippets/src/main/java/com/google/cloud/vision/ClassificationDeployModelNodeCount.java
  samples/snippets/src/main/java/com/google/cloud/vision/ClassificationUndeployModel.java
  samples/snippets/src/main/java/com/google/cloud/vision/ModelApi.java
  samples/snippets/src/main/java/com/google/cloud/vision/ObjectDetectionDeployModelNodeCount.java
  samples/snippets/src/main/java/com/google/cloud/vision/PredictionApi.java
  samples/snippets/src/test/java/com/google/cloud/vision/ClassificationDeployModelIT.java
  samples/snippets/src/test/java/com/google/cloud/vision/ObjectDetectionDeployModelNodeCountIT.java
  samples/snippets/src/test/java/com/google/cloud/vision/PredictionApiIT.java
Labels: api: automl, cla: yes, samples

#375 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#377 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: automerge, cla: yes

#379 chore(java): enable generated-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: automerge, cla: yes, context: full
