Repository googleapis/java-automl, pull requests merged in 2020-11, with the labels that each got.

#382 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#385 chore: version bump and clean up automl vision samples
  samples/snippets/src/main/java/com/google/cloud/vision/ClassificationDeployModel.java
  samples/snippets/src/main/java/com/google/cloud/vision/ClassificationDeployModelNodeCount.java
  samples/snippets/src/main/java/com/google/cloud/vision/ClassificationUndeployModel.java
  samples/snippets/src/main/java/com/google/cloud/vision/ModelApi.java
  samples/snippets/src/main/java/com/google/cloud/vision/ObjectDetectionDeployModelNodeCount.java
  samples/snippets/src/main/java/com/google/cloud/vision/PredictionApi.java
  samples/snippets/src/test/java/com/google/cloud/vision/ClassificationDeployModelIT.java
  samples/snippets/src/test/java/com/google/cloud/vision/PredictionApiIT.java
Labels: api: automl, cla: yes

#386 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#383 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#387 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#388 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#393 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#397 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#402 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#404 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full, samples
