Repository googleapis/java-automl, pull requests merged in 2020-09, with the labels that each got.

#286 samples: fixed flaky listmodel by increasing the timeout
  samples/snippets/src/main/java/com/example/automl/ListModels.java
Labels: cla: yes

#289 chore: regenerate README
  README.md
  synth.metadata
Labels: api: automl, cla: yes, context: none

#296 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#311 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#313 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#314 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: automl, automerge, cla: yes

#320 samples: small fix
  samples/snapshot/pom.xml
  samples/snippets/src/test/java/com/beta/automl/TablesGetModelTest.java
Labels: cla: yes

#321 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#323 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
