Repository googleapis/java-automl, pull requests merged in 2020-08, with the labels that each got.

#262 chore: regenerate README samples
  README.md
  samples/snippets/pom.xml
  synth.metadata
  synth.py
Labels: automerge, cla: yes, context: none

#265 chore: regenerate common templates
  .kokoro/continuous/dependencies.cfg
  .kokoro/continuous/integration.cfg
  .kokoro/continuous/java11.cfg
  .kokoro/continuous/java7.cfg
  .kokoro/continuous/java8-osx.cfg
  .kokoro/continuous/java8-win.cfg
  .kokoro/continuous/lint.cfg
  .kokoro/continuous/propose_release.cfg
  .kokoro/continuous/samples.cfg
  .kokoro/nightly/dependencies.cfg
  .kokoro/nightly/lint.cfg
  synth.metadata
  synth.py
Labels: automerge, cla: yes, context: partial

#266 build: update dependencies check to only check for runtime and compile scopes
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#270 chore: regenerate README
  README.md
  synth.metadata
Labels: cla: yes, context: none

#275 samples: add presubmit lint check
  .github/workflows/samples.yaml
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: partial

#278 build: temporarily disable reporting to unblock releases
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: automl, cla: yes, context: full

#280 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: cla: yes, context: full

#281 samples: refactor importDataset test service randomly throws cancel e…
  samples/snippets/src/test/java/com/example/automl/ImportDatasetTest.java
Labels: cla: yes
