Repository googleapis/java-automl, pull requests merged in 2020-06, with the labels that each got.

#210 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#213 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#215 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#220 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#225 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#226 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-automl/pom.xml
  grpc-google-cloud-automl-v1/pom.xml
  grpc-google-cloud-automl-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-automl-v1/pom.xml
  proto-google-cloud-automl-v1beta1/pom.xml
Labels: automerge, cla: yes

#233 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#239 fix: migrate to grpc_service_config
  README.md
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/AutoMlClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/AutoMlSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/AutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/AutoMlStubSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/GrpcAutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/PredictionServiceStubSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/AutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/AutoMlStubSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcAutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/PredictionServiceStubSettings.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/AutoMlClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/AutoMlClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#247 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
