Repository googleapis/java-automl, pull requests merged in 2021-05, with the labels that each got.

#679 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: none

#680 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: automl, automerge, cla: yes

#536 chore: added cleanup option in the setup ListOperationIT
  samples/snippets/src/test/java/com/example/automl/ListOperationStatusTest.java
Labels: api: automl, automerge, cla: yes

#694 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#695 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#696 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#698 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#699 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#704 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#707 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#709 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#706 chore: change GCP env to correct one
  samples/snippets/src/test/java/com/example/automl/ListOperationStatusTest.java
Labels: api: automl, cla: yes

#715 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes
