Repository googleapis/java-automl, pull requests merged in 2021-03, with the labels that each got.

#483 feat(generator): update protoc to v3.15.3
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/BatchPredictOperationMetadata.java
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/ExportDataOperationMetadata.java
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/Image.java
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/ImageOrBuilder.java
  proto-google-cloud-automl-v1beta1/clirr-ignored-differences.xml
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/BatchPredictOperationMetadata.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DataType.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DataTypeOrBuilder.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ExportDataOperationMetadata.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/Image.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ImageOrBuilder.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TablesModelMetadata.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TablesModelMetadataOrBuilder.java
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#486 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#487 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#490 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#491 chore(release): update Java microgenerator to 1.0.1
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/AutoMlClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/AutoMlSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/PredictionServiceClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/PredictionServiceSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/package-info.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/AutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/AutoMlStubSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/GrpcAutoMlCallableFactory.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/GrpcAutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/GrpcPredictionServiceCallableFactory.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/GrpcPredictionServiceStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/PredictionServiceStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/PredictionServiceStubSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/package-info.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/AutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/AutoMlStubSettings.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcAutoMlCallableFactory.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcAutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcPredictionServiceCallableFactory.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcPredictionServiceStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/PredictionServiceStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/PredictionServiceStubSettings.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/AutoMlClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/MockAutoMl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/MockAutoMlImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/MockPredictionService.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/MockPredictionServiceImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/PredictionServiceClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/AutoMlClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/MockAutoMl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/MockAutoMlImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/MockPredictionService.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/MockPredictionServiceImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/PredictionServiceClientTest.java
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/AnnotationSpecName.java
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/DatasetName.java
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/LocationName.java
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/ModelEvaluationName.java
  proto-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/ModelName.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AnnotationSpecName.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ColumnSpecName.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/DatasetName.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/LocationName.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelEvaluationName.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/ModelName.java
  proto-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/TableSpecName.java
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#492 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#494 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#495 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#497 chore: update gax-java dependency to 1.62
  grpc-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/AutoMlGrpc.java
  grpc-google-cloud-automl-v1/src/main/java/com/google/cloud/automl/v1/PredictionServiceGrpc.java
  grpc-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/AutoMlGrpc.java
  grpc-google-cloud-automl-v1beta1/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceGrpc.java
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#499 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#501 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#500 chore: deleted duplicate and unused region tags
  samples/snippets/src/main/java/com/google/cloud/translate/automl/DatasetApi.java
  samples/snippets/src/main/java/com/google/cloud/translate/automl/ModelApi.java
  samples/snippets/src/main/java/com/google/cloud/vision/ClassificationDeployModel.java
  samples/snippets/src/main/java/com/google/cloud/vision/ModelApi.java
  samples/snippets/src/test/java/com/google/cloud/translate/automl/ModelApiIT.java
  samples/snippets/src/test/java/com/google/cloud/vision/ClassificationDeployModelIT.java
Labels: api: automl, cla: yes

#505 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#506 chore: update java microgenerator to 1.0.2 Adds request initialization to sample code
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/AutoMlClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlClient.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/MockAutoMlImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/MockPredictionServiceImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/MockAutoMlImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/MockPredictionServiceImpl.java
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full, samples

#508 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#509 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#511 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#512 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#513 fix(samples): adds retry to TranslateCreateDatasetTest
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  samples/snippets/src/test/java/com/example/automl/TranslateCreateDatasetTest.java
Labels: api: automl, cla: yes, samples

#516 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full
