Repository googleapis/java-automl, pull requests merged in 2021-02, with the labels that each got.

#450 chore: cleaning up unused and redundant sampels and their ITs
  samples/snippets/src/main/java/beta/automl/GetModel.java
  samples/snippets/src/main/java/com/google/cloud/translate/automl/DatasetApi.java
  samples/snippets/src/main/java/com/google/cloud/translate/automl/ModelApi.java
  samples/snippets/src/main/java/com/google/cloud/vision/ObjectDetectionDeployModelNodeCount.java
  samples/snippets/src/test/java/com/google/cloud/translate/automl/DatasetApiIT.java
  samples/snippets/src/test/java/com/google/cloud/translate/automl/ModelApiIT.java
  samples/snippets/src/test/java/com/google/cloud/vision/ObjectDetectionDeployModelNodeCountIT.java
Labels: api: automl, cla: yes

#449 build(java): run linkage monitor as GitHub action
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#452 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#453 docs: generate sample code in the Java microgenerator
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/AutoMlClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/PredictionServiceClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/package-info.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/AutoMlClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/PredictionServiceClient.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/package-info.java
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full, samples

#456 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#435 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#457 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#462 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#461 chore: update gapic-generator-java to 0.0.20
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/GrpcAutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/stub/GrpcPredictionServiceStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcAutoMlStub.java
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/stub/GrpcPredictionServiceStub.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/MockAutoMlImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/MockPredictionServiceImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/MockAutoMlImpl.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/MockPredictionServiceImpl.java
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#463 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#465 build: reduce download junk in log files
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#464 chore: deleting duplicate samples
  samples/snippets/src/main/java/com/google/cloud/translate/automl/PredictionApi.java
  samples/snippets/src/test/java/com/google/cloud/translate/automl/PredictionApiIT.java
Labels: api: automl, cla: yes, samples

#466 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#469 chore: release gapic-generator-java v0.0.21 with gapic_metadata.json support
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1/gapic_metadata.json
  google-cloud-automl/src/main/java/com/google/cloud/automl/v1beta1/gapic_metadata.json
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#473 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#474 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#476 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#480 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes
