Repository googleapis/java-automl, pull requests merged in 2021-06, with the labels that each got.

#721 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#725 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#723 chore: release gapic-generator-java v1.0.10
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/AutoMlClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/PredictionServiceClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/AutoMlClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/PredictionServiceClientTest.java
  synth.metadata
Labels: api: automl, automerge, cla: yes, context: full

#732 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#734 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#733 chore: release gapic-generator-java v1.0.11
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/AutoMlClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1/PredictionServiceClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/AutoMlClientTest.java
  google-cloud-automl/src/test/java/com/google/cloud/automl/v1beta1/PredictionServiceClientTest.java
  synth.metadata
Labels: api: automl, cla: yes, context: full

#740 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#738 chore: migrate to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  google-cloud-automl-bom/pom.xml
  google-cloud-automl/clirr-ignored-differences.xml
  google-cloud-automl/pom.xml
  grpc-google-cloud-automl-v1/clirr-ignored-differences.xml
  grpc-google-cloud-automl-v1beta1/clirr-ignored-differences.xml
  owlbot.py
  pom.xml
  proto-google-cloud-automl-v1beta1/clirr-ignored-differences.xml
  samples/snippets/src/main/java/beta/automl/ImportDataset.java
  samples/snippets/src/main/java/beta/automl/ListDatasets.java
  samples/snippets/src/main/java/beta/automl/ListModels.java
  samples/snippets/src/main/java/com/example/automl/LanguageEntityExtractionPredict.java
  samples/snippets/src/main/java/com/example/automl/ListModels.java
  samples/snippets/src/main/java/com/google/cloud/translate/automl/DatasetApi.java
  samples/snippets/src/main/java/com/google/cloud/translate/automl/ModelApi.java
  samples/snippets/src/main/java/com/google/cloud/vision/PredictionApi.java
  samples/snippets/src/main/java/com/google/cloud/vision/samples/automl/ModelApi.java
  samples/snippets/src/test/java/beta/automl/CancelOperationTest.java
  samples/snippets/src/test/java/beta/automl/ImportDatasetTest.java
  samples/snippets/src/test/java/beta/automl/SetEndpointIT.java
  samples/snippets/src/test/java/beta/automl/TablesBatchPredictBigQueryTest.java
  samples/snippets/src/test/java/beta/automl/TablesCreateModelTest.java
  samples/snippets/src/test/java/beta/automl/VideoClassificationCreateModelTest.java
  samples/snippets/src/test/java/beta/automl/VideoObjectTrackingCreateModelTest.java
  samples/snippets/src/test/java/com/example/automl/ListModelsTest.java
  samples/snippets/src/test/java/com/example/automl/ListOperationStatusTest.java
  samples/snippets/src/test/java/com/google/cloud/translate/automl/DatasetApiIT.java
  synth.py
  versions.txt
Labels: api: automl, automerge, cla: yes

#743 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#750 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#751 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#755 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#756 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#762 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#763 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#765 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes

#769 chore: version bump
  samples/snippets/src/main/java/com/google/cloud/translate/automl/DatasetApi.java
  samples/snippets/src/main/java/com/google/cloud/translate/automl/ModelApi.java
Labels: api: automl, cla: yes

#770 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: automl, automerge, cla: yes
