Repository googleapis/java-automl, pull requests merged in 2021-09, with the labels that each got.

#889 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: automl, automerge

#893 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, kokoro:force-run, api: automl, automerge

#907 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes, api: automl, automerge

#922 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
  README.md
Labels: cla: yes, api: automl
